apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: core-system
  namespace: cicd
spec:
  description: CORE SYSTEM GitOps governance

  sourceRepos:
    - '*'

  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
