apiVersion: v1
kind: Service

metadata:
  name: fill-handler-service
  namespace: trading-infra

spec:
  selector:
    app: fill-handler-service

  ports:
    - protocol: TCP
      port: 8004
      targetPort: 8004
