apiVersion: v1
kind: Namespace

metadata:
  name: database

---
apiVersion: v1
kind: Service

metadata:
  name: timescaledb
  namespace: database

spec:
  selector:
    app: timescaledb

  ports:
    - port: 5432
      targetPort: 5432

---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: timescaledb
  namespace: database

spec:
  replicas: 1

  selector:
    matchLabels:
      app: timescaledb

  template:
    metadata:
      labels:
        app: timescaledb

    spec:
      containers:
        - name: timescaledb

          image: timescale/timescaledb:latest-pg16

          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_USER
              value: coreeye

            - name: POSTGRES_PASSWORD
              value: coreeye

            - name: POSTGRES_DB
              value: marketdata

          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"

            limits:
              cpu: "1000m"
              memory: "2Gi"
