apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: execution-isolation
  namespace: execution
spec:
  podSelector: {}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          domain: trading
  policyTypes:
  - Ingress
