apiVersion: v1
kind: Service

metadata:
  name: market-data-ingestion
  namespace: market-data

spec:
  selector:
    app: market-data-ingestion

  ports:
    - name: http
      port: 8000
      targetPort: 8000
