apiVersion: v1
data:
  KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
  KAFKA_CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
  KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
  KAFKA_DELETE_TOPIC_ENABLE: "true"
  KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
  KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
  KAFKA_LOG_DIRS: /var/lib/kafka/data
  KAFKA_LOG_RETENTION_HOURS: "168"
  KAFKA_LOG_SEGMENT_HOURS: "24"
  KAFKA_NUM_PARTITIONS: "6"
  KAFKA_PROCESS_ROLES: broker,controller
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"KAFKA_AUTO_CREATE_TOPICS_ENABLE":"false","KAFKA_CLUSTER_ID":"MkU3OEVBNTcwNTJENDM2Qk","KAFKA_CONTROLLER_LISTENER_NAMES":"CONTROLLER","KAFKA_DELETE_TOPIC_ENABLE":"true","KAFKA_INTER_BROKER_LISTENER_NAME":"PLAINTEXT","KAFKA_LISTENERS":"PLAINTEXT://:9092,CONTROLLER://:9093","KAFKA_LISTENER_SECURITY_PROTOCOL_MAP":"PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT","KAFKA_LOG_DIRS":"/var/lib/kafka/data","KAFKA_LOG_RETENTION_HOURS":"168","KAFKA_LOG_SEGMENT_HOURS":"24","KAFKA_NUM_PARTITIONS":"6","KAFKA_PROCESS_ROLES":"broker,controller"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"kafka-config","namespace":"kafka"}}
  creationTimestamp: "2026-05-25T21:45:12Z"
  name: kafka-config
  namespace: kafka
  resourceVersion: "73882"
  uid: e1aa9677-7882-49d1-aa4f-9cc2d0b7312d
