apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"n8n","namespace":"n8n"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"n8n"}},"template":{"metadata":{"labels":{"app":"n8n"}},"spec":{"containers":[{"env":[{"name":"N8N_SECURE_COOKIE","value":"false"},{"name":"GENERIC_TIMEZONE","value":"Asia/Kolkata"},{"name":"N8N_EDITOR_BASE_URL","value":"http://192.168.1.10:31678"},{"name":"WEBHOOK_URL","value":"http://192.168.1.10:31678"},{"name":"N8N_HOST","value":"0.0.0.0"},{"name":"N8N_PROTOCOL","value":"http"},{"name":"N8N_PORT","value":"5678"},{"name":"N8N_ENCRYPTION_KEY","valueFrom":{"secretKeyRef":{"key":"N8N_ENCRYPTION_KEY","name":"n8n-secret"}}}],"image":"docker.n8n.io/n8nio/n8n:2.22.4","imagePullPolicy":"Always","livenessProbe":{"httpGet":{"path":"/","port":5678},"initialDelaySeconds":20,"periodSeconds":15},"name":"n8n","ports":[{"containerPort":5678}],"readinessProbe":{"httpGet":{"path":"/","port":5678},"initialDelaySeconds":15,"periodSeconds":10},"volumeMounts":[{"mountPath":"/home/node/.n8n","name":"n8n-storage"}]}],"volumes":[{"name":"n8n-storage","persistentVolumeClaim":{"claimName":"n8n-data"}}]}}}}
  creationTimestamp: "2026-05-28T07:28:21Z"
  generation: 5
  name: n8n
  namespace: n8n
  resourceVersion: "1506442"
  uid: be42c818-8df9-4371-ae00-547b9d26699a
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: n8n
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2026-06-10T13:38:07Z"
      creationTimestamp: null
      labels:
        app: n8n
    spec:
      containers:
      - env:
        - name: N8N_SECURE_COOKIE
          value: "false"
        - name: GENERIC_TIMEZONE
          value: Asia/Kolkata
        - name: N8N_EDITOR_BASE_URL
          value: http://192.168.1.10:31678
        - name: WEBHOOK_URL
          value: http://192.168.1.10:31678
        - name: N8N_HOST
          value: 0.0.0.0
        - name: N8N_PROTOCOL
          value: http
        - name: N8N_PORT
          value: "5678"
        - name: N8N_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              key: N8N_ENCRYPTION_KEY
              name: n8n-secret
        image: docker.n8n.io/n8nio/n8n:2.22.4
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 5678
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 1
        name: n8n
        ports:
        - containerPort: 5678
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 5678
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /home/node/.n8n
          name: n8n-storage
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: n8n-storage
        persistentVolumeClaim:
          claimName: n8n-data
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2026-06-04T08:25:29Z"
    lastUpdateTime: "2026-06-04T08:25:29Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2026-05-28T07:28:21Z"
    lastUpdateTime: "2026-06-10T15:45:38Z"
    message: ReplicaSet "n8n-6968d7b8c6" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 5
  readyReplicas: 1
  replicas: 2
  unavailableReplicas: 1
  updatedReplicas: 1
