apiVersion: apps/v1
kind: Deployment

metadata:
  name: n8n
  namespace: n8n

spec:

  replicas: 1

  selector:
    matchLabels:
      app: n8n

  template:

    metadata:
      labels:
        app: n8n

    spec:

      containers:

      - name: n8n

        securityContext:
          runAsUser: 1000
          runAsGroup: 1000

        image: docker.n8n.io/n8nio/n8n:2.22.4

        imagePullPolicy: Always

        ports:
          - containerPort: 5678

        env:

          - name: N8N_SECURE_COOKIE
            value: "false"

          - name: GENERIC_TIMEZONE
            value: "Asia/Kolkata"

          - name: N8N_EDITOR_BASE_URL
            value: "http://192.168.1.10:31678"

          - name: WEBHOOK_URL
            value: "http://192.168.1.10:31678"

          - name: N8N_HOST
            value: "0.0.0.0"

          - name: N8N_PROTOCOL
            value: "http"

          - name: N8N_PORT
            value: "5678"

          - name: N8N_ENCRYPTION_KEY
            valueFrom:
              secretKeyRef:
                name: n8n-secret
                key: N8N_ENCRYPTION_KEY

        volumeMounts:

          - name: n8n-storage
            mountPath: /home/node/.n8n

        readinessProbe:
          httpGet:
            path: /
            port: 5678

          initialDelaySeconds: 15
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /
            port: 5678

          initialDelaySeconds: 20
          periodSeconds: 15

      volumes:

        - name: n8n-storage

          persistentVolumeClaim:
            claimName: n8n-data
