apiVersion: v1
kind: ServiceAccount
metadata:
  name: strategy-service
  namespace: strategy
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: execution-service
  namespace: execution
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: market-data-service
  namespace: market-data
