apiVersion: v1
kind: ServiceAccount
metadata:
  name: harbor-runtime
  namespace: cicd
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-runtime
  namespace: cicd
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cicd-deployer
  namespace: cicd
