apiVersion: apps/v1
kind: Deployment

metadata:
  name: market-data-normalizer
  namespace: market-data

spec:
  replicas: 1

  selector:
    matchLabels:
      app: market-data-normalizer

  template:
    metadata:
      labels:
        app: market-data-normalizer

    spec:
      containers:
        - name: market-data-normalizer

          image: market-data-normalizer:stage-12

          imagePullPolicy: Never

          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"

            limits:
              cpu: "500m"
              memory: "1Gi"
