global:
  domain: argocd.core.local

configs:
  params:
    server.insecure: true

server:
  ingress:
    enabled: true
    ingressClassName: kong
    hostname: argocd.core.local
    annotations:
      konghq.com/protocols: https
      konghq.com/https-redirect-status-code: "301"

controller:
  serviceAccount:
    create: false
    name: argocd-runtime

repoServer:
  serviceAccount:
    create: false
    name: argocd-runtime

applicationSet:
  enabled: true

redis:
  enabled: true
