apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: cicd
data:
  policy.default: role:readonly

  policy.csv: |
    p, role:admin, applications, *, */*, allow
    p, role:admin, clusters, *, *, allow
    p, role:admin, repositories, *, *, allow
    p, role:readonly, applications, get, */*, allow
