apiVersion: apps/v1
kind: Deployment

metadata:
  name: market-data-persistence
  namespace: market-data

spec:
  replicas: 1

  selector:
    matchLabels:
      app: market-data-persistence

  template:
    metadata:
      labels:
        app: market-data-persistence

    spec:
      containers:
        - name: market-data-persistence

          image: localhost:5000/market-data-persistence:stage-12-v2

          imagePullPolicy: Always

          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"

            limits:
              cpu: "500m"
              memory: "1Gi"
