apiVersion: 1

datasources:

  - name: Prometheus

    uid: prometheus

    type: prometheus

    access: proxy

    url: http://kube-prometheus-stack-prometheus.observability.svc.cluster.local:9090

    isDefault: true

  - name: Loki

    uid: loki

    type: loki

    access: proxy

    url: http://loki-gateway.observability.svc.cluster.local

  - name: Jaeger

    uid: jaeger

    type: jaeger

    access: proxy

    url: http://jaeger.observability.svc.cluster.local:16686

    jsonData:
      tracesToLogs:
        datasourceUid: loki

      tracesToMetrics:
        datasourceUid: prometheus

      nodeGraph:
        enabled: true
