apiVersion: v1
kind: Secret

metadata:
  name: penpot-postgres-secret
  namespace: tools

type: Opaque

stringData:
  POSTGRES_DB: penpot
  POSTGRES_USER: penpot
  POSTGRES_PASSWORD: penpot-postgres-password
