apiVersion: apps/v1
kind: Deployment

metadata:
  name: penpot-redis
  namespace: tools

spec:
  replicas: 1

  selector:
    matchLabels:
      app: penpot-redis

  template:
    metadata:
      labels:
        app: penpot-redis

    spec:
      containers:

      - name: redis

        image: redis:7.2

        args:
          - --appendonly
          - "yes"

        ports:
        - containerPort: 6379

        volumeMounts:
        - name: redis-storage
          mountPath: /data

      volumes:
      - name: redis-storage
        persistentVolumeClaim:
          claimName: penpot-redis-pvc
