apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storage
  namespace: cicd

spec:
  project: default

  source:
    repoURL: https://github.com/corei-org/core-platform-gitops.git
    targetRevision: main
    path: gitops/base/platform/storage

  destination:
    server: https://kubernetes.default.svc
    namespace: storage

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
