apiVersion: v1
kind: Service

metadata:
  name: smart-order-router
  namespace: execution

spec:
  selector:
    app: smart-order-router

  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
