apiVersion: v1
kind: ConfigMap

metadata:
  name: kafka-config
  namespace: kafka

data:
  KAFKA_CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"

  KAFKA_PROCESS_ROLES: "broker,controller"

  KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"

  KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"

  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"

  KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"

  KAFKA_LOG_DIRS: "/var/lib/kafka/data"

  KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"

  KAFKA_DELETE_TOPIC_ENABLE: "true"

  KAFKA_LOG_RETENTION_HOURS: "168"

  KAFKA_LOG_SEGMENT_HOURS: "24"

  KAFKA_NUM_PARTITIONS: "6"
