{
  "type": "record",
  "name": "FillEventV1",
  "namespace": "corei.events.fill.v1",

  "fields": [

    { "name": "event_id", "type": "string" },
    { "name": "event_type", "type": "string" },
    { "name": "event_version", "type": "string" },
    { "name": "timestamp", "type": "string" },
    { "name": "correlation_id", "type": "string" },
    { "name": "source_service", "type": "string" },
    { "name": "account_id", "type": "string" },

    {
      "name": "payload",
      "type": {
        "type": "record",
        "name": "FillPayload",

        "fields": [

          { "name": "order_id", "type": "string" },
          { "name": "fill_price", "type": "double" },
          { "name": "fill_quantity", "type": "double" }

        ]
      }
    }

  ]
}
