apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: kafka
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kafka
  serviceName: kafka-headless
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: '2026-05-26T13:29:09Z'
      creationTimestamp: null
      labels:
        app: kafka
    spec:
      containers:
      - args:
        - "cat <<KAFKAEOF > /tmp/server.properties\nnode.id=0\n\nprocess.roles=broker,controller\n\
          \ncontroller.quorum.voters=0@kafka-0.kafka-headless.kafka.svc.cluster.local:9093\n\
          \nlisteners=PLAINTEXT://0.0.0.0:9092,SASL_SSL://0.0.0.0:9094,CONTROLLER://0.0.0.0:9093\n\
          \nadvertised.listeners=PLAINTEXT://kafka.kafka.svc.cluster.local:9092,SASL_SSL://kafka.kafka.svc.cluster.local:9094\n\
          \nlistener.security.protocol.map=PLAINTEXT:PLAINTEXT,SASL_SSL:SASL_SSL,CONTROLLER:PLAINTEXT\n\
          \ncontroller.listener.names=CONTROLLER\n\ninter.broker.listener.name=PLAINTEXT\n\
          \nlog.dirs=/var/lib/kafka/data/logs\n\noffsets.topic.replication.factor=1\n\
          \ntransaction.state.log.replication.factor=1\n\ntransaction.state.log.min.isr=1\n\
          sasl.enabled.mechanisms=SCRAM-SHA-256\n\nlistener.name.sasl_ssl.scram-sha-256.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule\
          \ required;\n\nlistener.name.sasl_ssl.sasl.enabled.mechanisms=SCRAM-SHA-256\n\
          \nssl.keystore.location=/etc/kafka/tls/keystore.jks\n\nssl.truststore.location=/etc/kafka/tls/truststore.jks\n\
          KAFKAEOF\n\n/opt/kafka/bin/kafka-storage.sh format \\\n  --ignore-formatted\
          \ \\\n  --cluster-id $CLUSTER_ID \\\n  --config /tmp/server.properties\n\
          \nexec /opt/kafka/bin/kafka-server-start.sh \\\n  /tmp/server.properties\n"
        command:
        - /bin/bash
        - -c
        env:
        - name: CLUSTER_ID
          value: MkU3OEVBNTcwNTJENDM2Qk
        - name: KAFKA_OPTS
          value: -Djava.security.auth.login.config=/etc/kafka/security/kafka_jaas.conf
        image: apache/kafka:3.7.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 20
          successThreshold: 1
          tcpSocket:
            port: 9092
          timeoutSeconds: 1
        name: kafka
        ports:
        - containerPort: 9092
          name: broker
          protocol: TCP
        - containerPort: 9093
          name: controller
          protocol: TCP
        - containerPort: 9094
          name: sasl-ssl
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 9092
          timeoutSeconds: 1
        resources:
          limits:
            cpu: '1'
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
        securityContext:
          runAsGroup: 1000
          runAsUser: 1000
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/kafka/data
          name: kafka-data
        - name: kafka-runtime-tls
          mountPath: /etc/kafka/tls
          readOnly: true
        - name: kafka-security-runtime
          mountPath: /etc/kafka/security
          readOnly: true
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - sh
        - -c
        - 'mkdir -p /var/lib/kafka/data/logs


          chown -R 1000:1000 /var/lib/kafka/data/logs

          '
        image: busybox:1.36
        imagePullPolicy: IfNotPresent
        name: volume-permissions
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/kafka/data
          name: kafka-data
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
      terminationGracePeriodSeconds: 30
      volumes:
      - name: kafka-runtime-tls
        secret:
          secretName: kafka-runtime-tls
      - name: kafka-security-runtime
        secret:
          secretName: kafka-security-runtime
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      name: kafka-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
      volumeMode: Filesystem
    status:
      phase: Pending
