apiVersion: v1
kind: Service

metadata:
  name: mlflow
  namespace: research

spec:
  selector:
    app: mlflow

  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000

---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: mlflow
  namespace: research

spec:
  replicas: 1

  selector:
    matchLabels:
      app: mlflow

  template:

    metadata:
      labels:
        app: mlflow

    spec:

      containers:

        - name: mlflow

          image: mlflow:stage-12a-lite

          imagePullPolicy: Never

          env:
            - name: GUNICORN_CMD_ARGS
              value: "--workers=1"

          ports:
            - containerPort: 5000

          command:
            - mlflow

          args:
            - server
            - --host
            - 0.0.0.0
            - --port
            - "5000"
            - --workers
            - "1"
            - --backend-store-uri
            - sqlite:///mlflow.db
            - --default-artifact-root
            - /mlflow/artifacts

          volumeMounts:
            - mountPath: /mlflow
              name: mlflow-storage

          resources:
            requests:
              cpu: "10m"
              memory: "128Mi"

            limits:
              cpu: "100m"
              memory: "256Mi"

      volumes:
        - name: mlflow-storage

          hostPath:
            path: /home/coreeye/corei/research/mlflow
            type: DirectoryOrCreate
