apiVersion: v1
kind: Service

metadata:
  name: reconciliation-service
  namespace: trading-infra

spec:
  selector:
    app: reconciliation-service

  ports:
    - protocol: TCP
      port: 8005
      targetPort: 8005
