apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"n8n-nodeport","namespace":"n8n"},"spec":{"ports":[{"name":"http","nodePort":31678,"port":5678,"targetPort":5678}],"selector":{"app":"n8n"},"type":"NodePort"}}
    creationTimestamp: "2026-06-01T23:30:55Z"
    name: n8n-nodeport
    namespace: n8n
    resourceVersion: "876399"
    uid: 02f74619-8257-4674-bbc9-b0b99a07b2bb
  spec:
    clusterIP: 10.105.23.242
    clusterIPs:
    - 10.105.23.242
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      nodePort: 31678
      port: 5678
      protocol: TCP
      targetPort: 5678
    selector:
      app: n8n
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"n8n-service","namespace":"n8n"},"spec":{"ports":[{"port":5678,"targetPort":5678}],"selector":{"app":"n8n"},"type":"ClusterIP"}}
    creationTimestamp: "2026-05-28T07:28:21Z"
    name: n8n-service
    namespace: n8n
    resourceVersion: "371296"
    uid: bde867ab-5215-4e95-bbe5-3db30db2867c
  spec:
    clusterIP: 10.100.204.27
    clusterIPs:
    - 10.100.204.27
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 5678
      protocol: TCP
      targetPort: 5678
    selector:
      app: n8n
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
