recovery:

  metallb:
    rollback: supported

  ingress-nginx:
    rollback: supported

  cert-manager:
    rollback: supported

  longhorn:
    rollback: partial

  istio-base:
    rollback: supported
